# -*- coding: utf-8 -*-
"""list_slicing.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gAE5_LhfQ98mdtLOOHkwlf6t_yElektg
"""

# Task 2: Demonstrate List Slicing

def main():
    # 1. Create a list of numbers from 1 to 10
    # list(range(1, 11)) creates [1, 2, ..., 10]
    numbers = list(range(1, 11))

    # 2. Extract the first five elements
    # Syntax is list[start:end]. [:5] means start from 0 up to (but not including) index 5.
    first_five = numbers[:5]

    # 3. Reverse these extracted elements
    # [::-1] is a common Python idiom to reverse a list
    reversed_five = first_five[::-1]

    # 4. Print the results
    print(f"Original list: {numbers}")
    print(f"Extracted first five elements: {first_five}")
    print(f"Reversed extracted elements: {reversed_five}")

if __name__ == "__main__":
    main()