# -*- coding: utf-8 -*-
"""student_marks.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gAE5_LhfQ98mdtLOOHkwlf6t_yElektg
"""

# Task 1: Create a Dictionary of Student Marks

def main():
    # 1. Create a dictionary with student names and marks
    # You can add more students here if you like
    student_marks = {
        "Alice": 85,
        "Bob": 92,
        "Charlie": 78,
        "David": 65,
        "Eve": 90
    }

    # 2. Ask the user to input a student's name
    name = input("Enter the student's name: ")

    # 3. Retrieve and display the corresponding marks
    # We use .get() or a standard if-else check
    if name in student_marks:
        print(f"{name}'s marks: {student_marks[name]}")
    else:
        # 4. If the student’s name is not found, display a message
        print("Student not found.")

if __name__ == "__main__":
    main()